version: '2'

services:
    reverseproxy:
        build:
          context: ./nginx
        ports:
          - '80:80'
    test:
        image: sonatype/nexus3
        volumes:
          - nexus-data:/nexus-data
volumes:
  nexus-data:
    external:
      name: nexus-data
